export type CloudinaryAsset = {
  id: string;
  assetId: string;
  publicId: string;
  resourceType: string;
  format: string;
  width: number;
  height: number;
  bytes: number;
  url: string;
  secureUrl: string;
  createdAt: string;
  updatedAt: string;
  duration: null;
  frameRate: null;
  bitRate: null;
  playbackUrl: null;
  tags: string[];
  userId: string;
  displayName: string;
  starred: boolean;
};
